### PR TITLE
changes to support heater and spa mode

### PR DESCRIPTION
**Pull request by homebridge-fun**
I made key changes to enable support of additional functions of my setup - in hopes it will be useful to others...

### CODE REVIEW

**Comment by homebridge-fun** [comment]
I should have noted that the new features are support of switches for heater and spa mode (which is shown in the web UI as two separate buttons but in practice is a toggle.   I did successfully run the build and run on my pool and it works great.  Glad to be able to add to this great work...

**Comment by cupshir** [comment]
Thanks for taking the time to add these in!  Since I dont have a spa, I have a couple questions to better understand how these would be used.

1. Is one of these always active or can they both be off?  
2. When these are on, does it activate the filter pump or is that still separate?

File: tsconfig.json [hunk 1]
```diff
@@ -15,7 +15,9 @@
     "rootDir": "./src",
     "strict": true,
     "esModuleInterop": true,
-    "noImplicitAny": true
+//changes to handle build errors 
+//    "noImplicitAny": true
+    "noImplicitAny": false
```
Comment (cupshir) [inline tsconfig.json:20]: What build errors were you running into?  I would like to correct the errors vs turning this off.

**Comment by homebridge-fun** [comment]
> Thanks for taking the time to add these in! Since I dont have a spa, I have a couple questions to better understand how these would be used.
> 
> 1. Is one of these always active or can they both be off?
> 2. When these are on, does it activate the filter pump or is that still separate?

Happy to help!   This was a great baseline you set - so thank you!

The heat and spa buttons are distinct.    The spa button turns valves to change the water flow, changes the target temp of the heater to a spa target temp which is set separately from the target pool temp, and changes the filter speed to a preset value (might be Speed4 in my system).  When you hit spa again, it changes back to the normal scheduled pool pump speed, pool heater target value, and moves the valves back.   By the way, the pool and spa buttons do the same thing, the lights just toggle back and forth on the web interface, so I just called is spa mode and it is either on or off (which is equivalent to pool mode).   I don't know if some setups let you have both pool and spa mode active.

Heat enables or disengages the heater and is separate (at least on my system).   So if heat is turned off and you turn on spa mode, it still does the three actions I mentioned, but since the heater has not been enabled, it will not engage.

Similar for filter, it is a separate engage/disengage function (at least on mine)

File: tsconfig.json (hunk 1 above)
Comment (homebridge-fun) [reply tsconfig.json:20]: > What build errors were you running into? I would like to correct the errors vs turning this off.

Completely agree if another method would solve this.   Below is the error I received.   I also found this link to others receiving this error when creating new plug-in builds on homebridge 1.6... https://github.com/homebridge/HAP-NodeJS/issues/998 though the workaround they suggested didn't work when I tried to just create a declarations file, but there is probably a way I needed to refer to that declaration file.
__________________________________
pi@homebridge:~/development/homebridge-aqua-connect-lite $ npm run build

> homebridge-aqua-connect-lite@1.2.2 build
> rimraf ./dist && tsc

node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Advertiser.d.ts:5:29 - error TS7016: Could not find a declaration file for module '@homebridge/dbus-native'. '/home/pi/development/homebridge-aqua-connect-lite/node_modules/homebridge/node_modules/@homebridge/dbus-native/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/homebridge__dbus-native` if it exists or add a new declaration (.d.ts) file containing `declare module '@homebridge/dbus-native';`

5 import { InvokeError } from "@homebridge/dbus-native";
                              ~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Advertiser.d.ts:5
_____________________________________

**Comment by cupshir** [comment]
Thats helpful.  I just looked it up in the manual and found this info. Does your system toggle between Pool, Spa, and Spillover? Or just Pool & Spa?  I think a check is needed to ensure the correct system state is displayed in HomeKit.

From manual...
On a hardware terminal, Pool, Spa, and Spillover are three LEDs associated with one button. Pressing that button advances the Pool / Spa / Spillover setting to the next state. On the Remote Control page, it appears that there are three buttons but all three buttons function as one. Clicking on Pool does not select pool mode. Rather, clicking on Pool, Spa, or Spillover will advance the Pool / Spa / Spillover setting to the next state, just like on the hardware terminal.

File: tsconfig.json (hunk 1 above)
Comment (cupshir) [reply tsconfig.json:20]: Ok, Ill take a look tonight.

**Comment by homebridge-fun** [comment]
That is helpful info from the manual.   My 'Spillover' must be disabled - It only toggles between Pool and Spa.   If we decide to allow all three modes, I guess we would have to show all three options as virtual buttons and highlight the current active mode as 'on'?  Unless homekit/homebridge allows the plug in to put the text in the status where it could show the current state.  Unfortunately, I could not test that on my end as spillover is disabled.

**Comment by ifeign** [comment]
I think it could be displayed as an air filter or maybe even a shower valve with 4 speeds representing different modes (0%, 33%, 66%, 100%). Not ideal, but it's what we get with HomeKit sadly. If this was Home Assistant, things could be a lot more detailed 

Something like this combined shower accessory image

Edit: it occurred to me that a combined switch accessory is also a possibility, with the configuration you suggested

**Comment by homebridge-fun** [comment]
It might be nice for folks wiht only two modes to just be able to show one or the other by hiding the alternate button.  If you have all three, then it might only be an option to show all 3 I guess.   Better than the fan speed option I think at this point unforutnately.

**Comment by cupshir** [comment]
I will have to experiment, but I am leaning towards 3 separate toggle switches (each enabled through config, so those that don't have spa or spillover can hide them).  When you press the toggle switch, it will start cycling through the button presses until the screen displays the correct response.  Also, pressing 1 toggle switch, would turn off the other 2 toggle switches.  

I have a Sony receiver plug in that works similar. They didn't want to do an external accessory (im assuming), so they used toggle switches to change inputs and toggling on 1 switch, turns off the other switches.

Im hoping I can temporarily enable these features on my system so I can properly test.

**Comment by cupshir** [comment]
> I think it could be displayed as an air filter or maybe even a shower valve with 4 speeds representing different modes (0%, 33%, 66%, 100%). Not ideal, but it's what we get with HomeKit sadly. If this was Home Assistant, things could be a lot more detailed
> 
> Something like this combined shower accessory image
> 
> Edit: it occurred to me that a combined switch accessory is also a possibility, with the configuration you suggested

Is this screenshot from a Homebridge plugin? If it's a native HomeKit device, then I think they have more flexibility with piecing things together. 

Homebridge seems to have set definitions of what feautres accessories can have. As an example, at least per the Homebridge documentation, the faucet accessory doesn't have a temperature setting. 

Im not sure if Homebridge has a way of grouping accessories in the code, Im pretty sure its possible as I have seen other plugins do it, but Im still pretty new with plugin development.

**Comment by ifeign** [comment]
That is a native HomeKit shower controller by Moen

**Comment by homebridge-fun** [comment]
Unfortunately, most of these configurations are controlled by our installers.   I cannot enter the config menu to enable or disable features.   Unless, of course, your installer is willing to give you the info to unlock and reprogram your unit

**Comment by cupshir** [comment]
I was able to enable Spa and Spillover mode on my controller last night, so I think I have what I need to test basic functionality. 

Give me a bit to work on this. I created a feature branch from your PR and will add on to what you have already done.

Thanks!

**Comment by homebridge-fun** [comment]
Excellent - thanks!   I am happy to test on my system too if needed. Just let me know.

**Comment by ifeign** [comment]
> > I think it could be displayed as an air filter or maybe even a shower valve with 4 speeds representing different modes (0%, 33%, 66%, 100%). Not ideal, but it's what we get with HomeKit sadly. If this was Home Assistant, things could be a lot more detailed
> 
> > 
> 
> > Something like this combined shower accessory image
> 
> > 
> 
> > Edit: it occurred to me that a combined switch accessory is also a possibility, with the configuration you suggested
> 
> 
> 
> Is this screenshot from a Homebridge plugin? If it's a native HomeKit device, then I think they have more flexibility with piecing things together. 
> 
> 
> 
> Homebridge seems to have set definitions of what feautres accessories can have. As an example, at least per the Homebridge documentation, the faucet accessory doesn't have a temperature setting. 
> 
> 
> 
> Im not sure if Homebridge has a way of grouping accessories in the code, Im pretty sure its possible as I have seen other plugins do it, but Im still pretty new with plugin development.  

It is possible for Homebridge to create grouped accessories, I forgot to share this example from the OnStar plugin. The Neato plugin is also similar image
image

**Comment by cupshir** [comment]
Im still working on this, I was able to get proof of concept working where it toggles the mode, parses response, and toggles again if needed, but there are still some quirks I have to work out. Like, the Aquaconnect device doesn't seem to respond to super fast button presses, so I need to gracefully delay the button presses.  

For your system none of this matters since you don't have spillover, so the button press will always toggle between pool/spa.  But I want to be thorough and make sure it will work for anyone who tries to use it.

Grouping might not be possible without a major change to how the accessories are published, but this should be pretty minor cause you can manually group the "switch" type accessories from the Home app. And the new buttons are all switches.  Ill post an update when the switches are working so you don't have to wait for me to learn how to group stuff.

Thanks for your patience!

**Comment by homebridge-fun** [comment]
Sounds great.   Thank you!

**Comment by cupshir** [comment]
I just pushed a bunch of updates to a new branch called "feature-spa-heater-functionality".  Are you able to test the changes from that branch or do you need me to deploy a release?  

Everything tested good on my end, but would love to get a second test before pushing to main branch if possible. No biggie if not possible, just let me know.

In a nutshell, I had to refactor quite a bit to best support the mode toggling and having many accessories enabled. At one point Homebridge was spamming/overwhelming the AquaConnect bridge with so many requests it was knocking the bridge offline.  So I had to build in delay functionality as well as cacheing to alleviate the requests to the AquaConnect bridge. There are new settings to configure these delays, so you can set them as small as your system will handle or increase them if you find the AquaConnect bridge is not responding.

Let me know if you have questions and hope testing goes well!

**Comment by homebridge-fun** [comment]
Thanks for all of the work!   Just pulled from the branch, compiled and installed.   Seems like everything works, but the toggle between pool and spa is not very good.   In that when I switch, it keeps the 'other' mode lit up for minutes unless i click into the opposite mode which seems to force an update.    When I only had a button to turn spa on or off, it didn't have this, because it wasn't trying to keep track of the pool 'switch'.   

I tried only enabling a single mode - SPA in my case to try to get back to the behavior I had in this branch, but in that case, it does not seem to make any change.

I checked in the accessories area of homebridge and it refreshes quickly there.   So perhaps this is just a homekit issue?   Is there a way to push updates to make the refresh happen?  Otherwise, it may be better to just enable a single switch like spa so users can toggle it on and off - with the obvious downside that it never says that 'pool' mode is on, but that may be better than have multiple modes appear to be on for an extended period.

**Comment by cupshir** [comment]
Ill look into why the other modes are taking minutes to update. I only tested in Homebridge interface, so that explains why I missed it.

The way I built the modes, if you press a mode thats already on, the button press is ignored, which is why it is not doing anything.

Is the expected behavior when Spa mode is on, when you press the Spa button it goes back to pool mode?

Thanks



Thanks,
Christopher Upshir
________________________________

**Comment by homebridge-fun** [comment]
Makes sense - and thanks for looking into it.   If I enable both Pool and Spa in the config and then turn on spa. It seems to turn on (albeit the delay I mentioned).   If I hit spa again, it will not turn off spa.   In homekit and homebridge, it turns off both pool and spa and does not change the mode in the physical pool.   Eventually, both the homebridge interface and homekit reflect that it is still on spa.

**Comment by homebridge-fun** [comment]
OK - so I got more time to actively use the system and realized an issue on the heater :(    

When I turn the heater 'On", it turns on Auto Mode which automatically cycles the heater on and off based on the target temp.  

When I first turn it on, it works exactly as expected.   Unfortunately, once it hits the target temperature, the web app status changes from "WEBS_ON" to "WEBS_OFF" and the color changes as well back to gray.    So homekit then indicates that the heater is off - which is true that it is not running, but the automatic heating is still active.   This appears to be a difference between the status that the WebApp shows and what the iOS app shows.   In the iOS app, the heater button shows 'Auto' when the heater is in automatic mode, but the web app does not display this status.   In iOS, the color says whether the heater is actively running (which is similar to the webapp), but the iOS app shows a status of OFF or AUTO.   In the current model, this branch could lead to confusion.    To accurately show the heater status, it looks like we will have to read the values from the display (similar to temp) and keep track of the heater status. 

When the heater is in Auto mode, the status display shows this in html (removed outer <> to not convert to simple text):
td id="Lcd_00" class="WEBS_TEXT_DISPLAY c1" onclick="ProcessConfigInput()" valign="bottom">      Heater1       </td
td id="Lcd_01" class="WEBS_TEXT_DISPLAY c1" onclick="ProcessConfigInput()" valign="top">    Auto Control    </td>
When the heater is taken out of Auto mode, the html status looks like this:
td id="Lcd_00" class="WEBS_TEXT_DISPLAY c1" onclick="ProcessConfigInput()" valign="bottom">      Heater1       </td
td id="Lcd_01" class="WEBS_TEXT_DISPLAY c1" onclick="ProcessConfigInput()" valign="top">     Manual Off     </td

**Comment by cupshir** [comment]
I really wish Homekit let us control custom text statuses on accessories, would make this so much easier.  

Without putting a lot of thought into it, I think the easiest way is to have 2 switches for the Heater, 1 for Off / Auto and the other for the actual heater turning on and off.

Couple questions...

1. If the Heater is in Auto mode and the heater is on. What happens when you press the heater button to turn it off? Does the heater stay in Auto mode and turn the heater off? Or does it also turn off Auto mode?

2. If the Heater is in Auto mode and the heater is off. What happens when you press the heater button to turn it on? Does it stay in Auto mode AND turn the heater turns on?

I have fixed the issue with Homekit not updating the modes, but need to test some before I push it here for further testing.

**Comment by homebridge-fun** [comment]
Really great to hear about your progress on the HomeKit status updates!

On the heater modes - pushing the button only turns the heater back and forth between Auto and Off.   The behavior is unchanged whether or not the heater is in the on or off at the time of the button press.  

There is no manual way to force the heater on and off other than to turn Auto on or off and adjust the temp.  Similar to a house thermostat.  If the heater is in Auto and not currently running because it has reached the target temp, the only way to force the heater to start is to increase the target temp.  

Specific answers to your questions
______
If the Heater is in Auto mode and the heater is on. What happens when you press the heater button to turn it off? Does the heater stay in Auto mode and turn the heater off? Or does it also turn off Auto mode?

Turning it off in the scenario would turn the heater from Auto to Off which would stop the heater from running as well.  

______
If the Heater is in Auto mode and the heater is off. What happens when you press the heater button to turn it on? Does it stay in Auto mode AND turn the heater turns on?

This would also turn it from Auto to off.
